version: '2'

networks:
  app-tier:
    driver: bridge

services:
  phpfpm:
    image: USERNAME/phpfpm-app:0.1.0
    networks:
      - app-tier
  nginx:
    image: 'bitnami/nginx:1.19-debian-10'
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./server_blocks:/opt/bitnami/nginx/conf/server_blocks
  mariadb:
    image: bitnami/mariadb:latest
    environment:
        - MARIADB_USER=mini
        - MARIADB_PASSWORD=mini
        - MARIADB_DATABASE=mini
        - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
